language: php

sudo: false

env:
  global:
    - PREFER="--prefer-dist"

matrix:
    fast_finish: true
    include:
        - php: 7.2.5
        - php: 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer update --no-interaction $PREFER

script:
  - composer test
